# data visualization the graphical repesentation of information using elements like chsrtd,graphd and maps

In [4]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
print(np.__version__)

2.0.2


In [9]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
c=np.array([[[1,2,3]],
 [[4,5,6]],
  [[7,8,9]]
            ])
print(c)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [26]:
d=np.zeros([3,3])

In [27]:
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
d=np.full([3,3],8)

In [29]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
def greet():
  """ this is for testing doc string"""
  print("testing function")
  print("testing function")
  pritn(greet())

In [36]:
print(greet.__doc__)

 this is for testing doc string


In [37]:
e=np.eye(4)
print(a,b,c,e,d)

[1 2 3 4] [[1 2 3]
 [4 5 6]
 [7 8 9]] [[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]] [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] [[8 8 8]
 [8 8 8]
 [8 8 8]]


In [38]:
f=np.arange(2,10,3)
print(f)

[2 5 8]


In [40]:
np.linspace(2,10,12)

array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        ])

In [44]:
np.random.randn(3,3)

array([[-0.76749259,  1.3620411 , -1.00394146],
       [-0.38245378,  0.19385816, -1.55783387],
       [ 0.15089166,  0.86391745, -0.3691024 ]])

In [45]:
arr=np.array([["a","b","c","d","e"],[1,2,3,4,5]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

(2, 5)
2
10
<U21
84
840


In [47]:
a=np.array([10,20,30,40,50])
print(a[0])
print(a[2])
print(a[-1])

print(a[1:4])
print(a[:3])
print(a[::2])
print(a[::-1])


10
30
50
[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [50]:
arr=np.array([1,2,3,4,5,56,78,])

In [62]:
print(arr[:2])

[1 2]


In [63]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m[0,0])
print(m[1,2])
print(m[0,:])
print(m[:,1])
print(m[0:2,1:3])

1
6
[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


In [64]:
a=np.array([10,25,8,42,17])

mask=a>15
print(mask)
print(a[mask])
print(a[a>15])
print(a[[0,3]])

[False  True False  True  True]
[25 42 17]
[25 42 17]
[10 42]
